#include <iostream>
#include <string>
using namespace std;

class Games {
    private:
        string title;
        string platform_type;
        string genre;
        float rating;
    public:
        Games(string t, string p, string g, float r) : title(t), platform_type(p), genre(g), rating(r) {}
        //setters
        string getTitle() const { return title; }
        string getPlatformType() const { return platform_type; }
        string getGenre() const { return genre; }
        float getRating() const { return rating; }
        //setters
        void setTitle(const string& t) { title = t; }
        void setPlatformType(const string& p) { platform_type = p; }
        void setGenre(const string& g) { genre = g; }
        void setRating(float r) { rating = r; }

        //binary heap functions (these were autogenerated as examples but put whatever you need)
        void insert(const Games& game);
        Games extractMax();
        bool isEmpty() const;

        //merge sort functions
};